package com.jiuqi.dna.core.internal.da.sqlbuffer;

public enum SqlFunction {

	CHR, NCHR, ASCII, LEN, INDEXOF, LOWER, UPPER, LTRIM, RTRIM, TRIM, SUBSTR, REPLACE, ROW_COUNT, NEW_RECID, TO_INT, TO_CHAR, BIN_TO_CHAR, BIN_LEN, BIN_SUBSTR, BIN_CONCAT, STR_CONCAT, GROUPING, LPAD, RPAD
}
