create or replace package dna is
type ref_cursor is ref cursor;
function year(ts timestamp) return number;
function quarter(ts timestamp) return number;
function month(ts timestamp) return number;
function weekofyear(ts timestamp) return number;
function dayofyear(ts timestamp) return number;
function dayofmonth(ts timestamp) return number;
function dayofweek(ts timestamp) return number;
function dayofweek_iso(ts timestamp) return number;
function hour(ts timestamp) return number;
function minute(ts timestamp) return number;
function second(ts timestamp) return number;
function millisecond(ts timestamp) return number;
function yearadd(ts timestamp, n number) return timestamp;
function quarteradd(ts timestamp, n number) return timestamp;
function monthadd(ts timestamp, n number) return timestamp;
function weekadd(ts timestamp, n number) return timestamp;
function dayadd(ts timestamp, n number) return timestamp;
function houradd(ts timestamp, n number) return timestamp;
function minuteadd(ts timestamp, n number) return timestamp;
function secondadd(ts timestamp, n number) return timestamp;
function yeardiff(st timestamp, ed timestamp) return number;
function quarterdiff(st timestamp, ed timestamp) return number;
function monthdiff(st timestamp, ed timestamp) return number;
function weekdiff(st timestamp, ed timestamp) return number;
function weekdiff_iso(st timestamp, ed timestamp) return number;
function daydiff(st timestamp, ed timestamp) return number;
function isleapyear(ts timestamp) return number;
function isleapmonth(ts timestamp) return number;
function isleapday(ts timestamp) return number;
function truncyear(ts timestamp) return timestamp;
function truncquarter(ts timestamp) return timestamp;
function truncmonth(ts timestamp) return timestamp;
function truncweek(ts timestamp) return timestamp;
function truncweek_iso(ts timestamp) return timestamp;
function truncday(ts timestamp) return timestamp;
function current_time_millis return number;
function hex_len16(n number) return varchar2;
function new_recid return raw;
function collate_gbk(s varchar2) return raw;
procedure silent_drop_table(tn varchar2);
procedure current_transaction_id(tid out number);
end dna;